### ISSUE TITLE
Problem building ruby 2.2.1

### ISSUE THREAD

**Issue by aharpervc** [rake-compiler/rake-compiler#112]
I'm trying to get cross compile working for ruby 2.2.1 and I've run into a problem. I'm using 0.9.5 and building with ruby 2.0.

running:
`rake-compiler cross-ruby VERSION=2.2.1 HOST=i686-w64-mingw32 debugflags="-g"`
(or, with `HOST=x86_64-w64-mingw32`)

fails with:
```
... success up to here...

installing extension headers: /home/vagrant/.rake-compiler/ruby/x86_64-w64-mingw32/ruby-2.2.1/include/ruby-2.2.0/ruby
installing default gems:      /home/vagrant/.rake-compiler/ruby/x86_64-w64-mingw32/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.2.6
                              io-console 0.4.3
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /home/vagrant/.rake-compiler/ruby/x86_64-w64-mingw32/ruby-2.2.1/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
/home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fiddle/import.rb:85:in `rescue in block in dlload': can't load advapi32 (Fiddle::DLError)
        from /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fiddle/import.rb:82:in `block in dlload'
        from /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fiddle/import.rb:73:in `collect'
        from /home/vagrant/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fiddle/import.rb:73:in `dlload'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:48:in `<module:AdvApi32>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:46:in `<module:SecureRandom>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/securerandom.rb:42:in `<top (required)>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/resolv.rb:6:in `<top (required)>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/remote_fetcher.rb:6:in `<top (required)>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/spec_fetcher.rb:1:in `<top (required)>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/dependency_installer.rb:5:in `<top (required)>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/lib/rubygems.rb:556:in `install'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:722:in `block (2 levels) in <main>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:721:in `each'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:721:in `block in <main>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:757:in `call'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:757:in `block in <main>'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:754:in `each'
        from /home/vagrant/.rake-compiler/sources/ruby-2.2.1/tool/rbinstall.rb:754:in `<main>'
```

I guess `advapi32` is a windows library (it's referenced here as shown in the stack trace https://www.omniref.com/ruby/2.2.1/symbols/SecureRandom::AdvApi32). 

Ruby 2.1 builds ok, and inspecting securerandom for 2.1 I see that its `advapi32` access is wrapped in a begin/rescue block in a way that 2.2 doesnt: https://www.omniref.com/ruby/2.1.0/symbols/SecureRandom?d=74832831

Short of patching 2.2.1's securerandom.rb to survive this reference problem, how can I get 2.2.1 to build? I'm not very familiar with how cross compile works with regards to windows dependencies.

I'm using rake-compile-dev-box (which installs the mingw toolchain) but for diagnostics and so forth I'm in that VM running this command manually. This is ultimately about getting [tiny_tds 0.6.3 packaged for windows](https://github.com/rails-sqlserver/tiny_tds/issues/196).

Any thoughts on how to get this working?

**Comment by kou** [comment]
Could you try to install Wine? It has advapi32.dll.

**Comment by aharpervc** [comment]
@kou I tried `sudo apt-get install wine` if that's what you meant, same error. I don't know if I need to point rake-compiler at wine or how that would work.

**Comment by aharpervc** [comment]
I modified securerandom.rb to survive windows library load failures while cross compiling.... it works, but I don't know what the "right" way to handle this is. https://gist.github.com/aharpervc/e2675cc13ef000d8c791

**Comment by kou** [comment]
Ruby 2.2.2 will be fixed the problem.
See also: tjschuck/rake-compiler-dev-box#20
