### ISSUE TITLE
Fails to build any gem, undefined method split on ruby_version

### ISSUE THREAD

**Issue by ilovemysillybanana** [rake-compiler/rake-compiler#143]
Trying to build any gem with this gem fails because of an issue here:

https://github.com/rake-compiler/rake-compiler/blob/v1.0.4/lib/rake/extensiontask.rb#L515

ruby version: 
2.3.1
rake-compiler version:
1.0.4

Output:
```
jose@jose-desktop:~/Workspace/Ruby/ruby-unf_ext (master)$ rake native gem --trace
** Invoke native (first_time)
** Invoke native:x86_64-linux (first_time)
** Invoke native:unf_ext:x86_64-linux (first_time)
** Invoke tmp/x86_64-linux/stage/lib/unf_ext.so (first_time)
** Invoke copy:unf_ext:x86_64-linux:2.3.1 (first_time)
** Invoke lib (first_time, not_needed)
** Invoke tmp/x86_64-linux/unf_ext/2.3.1/unf_ext.so (first_time, not_needed)
** Invoke tmp/x86_64-linux/unf_ext/2.3.1 (first_time, not_needed)
** Invoke tmp/x86_64-linux/unf_ext/2.3.1/Makefile (first_time, not_needed)
** Invoke tmp/x86_64-linux/unf_ext/2.3.1 (not_needed)
** Invoke ext/unf_ext/extconf.rb (first_time, not_needed)
** Invoke ext/unf_ext/unf.cc (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/lib (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/.document (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (first_time, not_needed)
** Invoke .document (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/.gitignore (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke .gitignore (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/.travis.yml (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke .travis.yml (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/CHANGELOG.md (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke CHANGELOG.md (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/Gemfile (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke Gemfile (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/LICENSE.txt (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke LICENSE.txt (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/README.md (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke README.md (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/Rakefile (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke Rakefile (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/extconf.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext (first_time, not_needed)
** Invoke ext/unf_ext/extconf.rb (not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf.cc (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext (not_needed)
** Invoke ext/unf_ext/unf.cc (not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/normalizer.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf (first_time, not_needed)
** Invoke ext/unf_ext/unf/normalizer.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/table.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf (not_needed)
** Invoke ext/unf_ext/unf/table.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/trie/char_stream.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/trie (first_time, not_needed)
** Invoke ext/unf_ext/unf/trie/char_stream.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/trie/node.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/trie (not_needed)
** Invoke ext/unf_ext/unf/trie/node.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/trie/searcher.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/trie (not_needed)
** Invoke ext/unf_ext/unf/trie/searcher.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf/util.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/ext/unf_ext/unf (not_needed)
** Invoke ext/unf_ext/unf/util.hh (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/lib/unf_ext.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/lib (not_needed)
** Invoke lib/unf_ext.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/lib/unf_ext/version.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/lib/unf_ext (first_time, not_needed)
** Invoke lib/unf_ext/version.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/test/helper.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/test (first_time, not_needed)
** Invoke test/helper.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/test/normalization-test.txt (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/test (not_needed)
** Invoke test/normalization-test.txt (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/test/test_unf_ext.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/test (not_needed)
** Invoke test/test_unf_ext.rb (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage/unf_ext.gemspec (first_time, not_needed)
** Invoke tmp/x86_64-linux/stage (not_needed)
** Invoke unf_ext.gemspec (first_time, not_needed)
** Execute copy:unf_ext:x86_64-linux:2.3.1
install -c tmp/x86_64-linux/unf_ext/2.3.1/unf_ext.so lib/unf_ext.so
cp tmp/x86_64-linux/unf_ext/2.3.1/unf_ext.so tmp/x86_64-linux/stage/lib/unf_ext.so
** Execute tmp/x86_64-linux/stage/lib/unf_ext.so
** Execute native:unf_ext:x86_64-linux
rake aborted!
NoMethodError: undefined method `split' for nil:NilClass
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:515:in `ruby_api_version'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-compiler-1.0.4/lib/rake/extensiontask.rb:262:in `block in define_native_tasks'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/jose/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/jose/.rbenv/versions/2.3.1/bin/rake:23:in `load'
/home/jose/.rbenv/versions/2.3.1/bin/rake:23:in `<main>'
Tasks: TOP => native => native:x86_64-linux => native:unf_ext:x86_64-linux
```

**Comment by kou** [comment]
How to reproduce this?

**Comment by ilovemysillybanana** [comment]
@kou you can pull any gem and then try to compile it.

```
gem fetch nokogiri
cd nokogiri
rake native gem
```

It will crash

**Comment by kou** [comment]
You need to install Ruby for cross compile: https://github.com/rake-compiler/rake-compiler#ive-got-my-tool-chain-installed-now-what

**Comment by kou** [comment]
rake-compiler-dock may help you: https://github.com/rake-compiler/rake-compiler#the-easy-way
