### ISSUE TITLE
rake-compiler v1.1.2 has broken something in Nokogiri's native gem builds

### ISSUE THREAD

**Issue by flavorjones** [rake-compiler/rake-compiler#195]
rake-compiler v1.1.2 has broken something in Nokogiri's native gem builds.

An example failure is at https://github.com/sparklemotion/nokogiri/runs/4458677557?check_suite_focus=true, which is running in the larskanis/rake-compiler-dock-mri-x86_64-darwin:1.1.0 image.

You can reproduce this by cloning sparklemotion/nokogiri and running `bundle exec rake gem:x86_64-darwin` (though please make sure you're using rake-compiler 1.1.2 or 1.1.3, since I'm locking to 1.1.1 in https://github.com/sparklemotion/nokogiri/pull/2383).

```
...
/usr/local/rvm/rubies/ruby-2.5.9/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/nokogiri/extconf.rb  --enable-cross-build
Could not find racc-1.6.0 in any of the sources
Run `bundle install` to install missing gems.
*** ../../../../ext/nokogiri/extconf.rb failed ***
```

I've bisected the problem to f48d669 but have been unable to understand what the root cause of this, other than noting that removing the siteconf file allows the build to proceed.

**Comment by flavorjones** [comment]
I'll also note that only the darwin build seems to be affected, as linux and windows builds seem to be fine. :monocle_face:

**Comment by kou** [comment]
Umm... #191 has many problems...

BTW, is https://github.com/sparklemotion/nokogiri/runs/4458677557?check_suite_focus=true#step:5:212 related to this? It seems that it's a Bundler or Racc related problem.

```text
/usr/local/rvm/gems/ruby-2.5.8/gems/bundler-2.2.3/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find racc-1.6.0 in any of the sources (Bundler::GemNotFound)
```

**Comment by flavorjones** [comment]
> BTW, is https://github.com/sparklemotion/nokogiri/runs/4458677557?check_suite_focus=true#step:5:212 related to this? It seems that it's a Bundler or Racc related problem.

Yes, this is the problem that I'm reporting here. Something in the siteconf file causes the `racc` gem to not be found, and I could not figure out what exactly is causing it. Environment variables all look right (GEM_HOME, GEM_PATH) and the gem is in fact installed; and this problem does not happen on linux or windows cross-compilation.

**Comment by flavorjones** [comment]
I've reproduced this issue in a much simpler gem, which is the "precompiled" gem in https://github.com/flavorjones/ruby-c-extensions-explained

See https://github.com/flavorjones/ruby-c-extensions-explained/pull/6 for the PR that introduces "racc" as a dependency and demonstrates this exact failure, but only with Darwin (and not Linux or Windows):

https://github.com/flavorjones/ruby-c-extensions-explained/runs/4483674590?check_suite_focus=true

```
/usr/local/rvm/rubies/ruby-2.5.8/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/precompiled/extconf.rb --enable-cross-build
/usr/local/rvm/gems/ruby-2.5.8/gems/bundler-2.2.3/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find racc-1.6.0 in any of the sources (Bundler::GemNotFound)
```

Note that without "racc" everything passes: https://github.com/flavorjones/ruby-c-extensions-explained/actions/runs/1563475900

**Comment by kou** [comment]
Could you try 1.1.4?

**Comment by konsolebox** [comment]
In my gem, rake-compiler installs extension (.so) to lib/ instead of lib/gem-name/ (extension source is in ext/gem-name/) during test (which has :compile as dependency).  It works fine with 1.1.1 and 1.1.2 but broken with 1.1.3.  I'm yet to examine this more thoroughly but this might be related.

**Comment by flavorjones** [comment]
@kou rake-compiler v1.1.4 does not fix this issue.

An easy way to reproduce this is to use the branch from https://github.com/flavorjones/ruby-c-extensions-explained/pull/6 and update the version of rake-compiler declared in the Gemfile.

The full output from that gem, using v1.1.4:

```text
$ be rake gem:x86_64-darwin
rake-compiler-dock bash -c "gem install bundler --no-document &&\nbundle &&\nbundle exec rake gem:x86_64-darwin:buildit\n"
Fetching bundler-2.2.33.gem
Successfully installed bundler-2.2.33
1 gem installed
Fetching gem metadata from https://rubygems.org/....
Fetching rake 13.0.6
Installing rake 13.0.6
Using bundler 2.2.33
Fetching rake-compiler-dock 1.1.0
Using mini_portile2 2.7.1
Fetching rake-compiler 1.1.4
Fetching minitest 5.14.4
Fetching racc 1.6.0
Installing rake-compiler-dock 1.1.0
Installing rake-compiler 1.1.4
Installing minitest 5.14.4
Installing racc 1.6.0 with native extensions
Using rcee_precompiled 0.3.0 from source at `.`
Bundle complete! 5 Gemfile dependencies, 8 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
no configuration section for specified version of Ruby (rbconfig-x64-mingw32-3.0.0)
no configuration section for specified version of Ruby (rbconfig-x64-mingw32-2.7.0)
no configuration section for specified version of Ruby (rbconfig-x64-mingw32-2.6.0)
no configuration section for specified version of Ruby (rbconfig-x64-mingw32-2.5.0)
no configuration section for specified version of Ruby (rbconfig-x86_64-linux-3.0.0)
no configuration section for specified version of Ruby (rbconfig-x86_64-linux-2.7.0)
no configuration section for specified version of Ruby (rbconfig-x86_64-linux-2.6.0)
no configuration section for specified version of Ruby (rbconfig-x86_64-linux-2.5.0)
no configuration section for specified version of Ruby (rbconfig-arm64-darwin-3.0.0)
no configuration section for specified version of Ruby (rbconfig-arm64-darwin-2.7.0)
no configuration section for specified version of Ruby (rbconfig-arm64-darwin-2.6.0)
no configuration section for specified version of Ruby (rbconfig-arm64-darwin-2.5.0)
cd tmp/x86_64-darwin/precompiled/3.0.0
/usr/local/rvm/rubies/ruby-2.5.9/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/precompiled/extconf.rb --enable-cross-build
Could not find racc-1.6.0 in any of the sources
Run `bundle install` to install missing gems.
*** ../../../../ext/precompiled/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=../../../../ext/precompiled
	--curdir
	--ruby=/usr/local/rake-compiler/ruby/x86_64-apple-darwin/ruby-3.0.0/bin/$(RUBY_BASE_NAME)
rake aborted!
Command failed with status (7): [/usr/local/rvm/rubies/ruby-2.5.9/bin/ruby ...]
/usr/local/rvm/gems/ruby-2.5.9/gems/rake-compiler-1.1.4/lib/rake/extensiontask.rb:216:in `block (2 levels) in define_compile_tasks'
/usr/local/rvm/gems/ruby-2.5.9/gems/rake-compiler-1.1.4/lib/rake/extensiontask.rb:213:in `block in define_compile_tasks'
/home/flavorjones/code/oss/ruby-c-extensions-explained/precompiled/Rakefile:50:in `block (4 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.5.9/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.9/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-2.5.9/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => native:x86_64-darwin => native:rcee_precompiled:x86_64-darwin => tmp/x86_64-darwin/stage/lib/rcee/precompiled/3.0/precompiled.bundle => copy:precompiled:x86_64-darwin:3.0.0 => tmp/x86_64-darwin/precompiled/3.0.0/precompiled.bundle => tmp/x86_64-darwin/precompiled/3.0.0/Makefile
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [docker run -v /home/flavorjones/code/oss/ruby-c-extensions-explained/precompiled:/home/flavorjones/code/oss/ruby-c-extensions-explained/precompiled -e UID\=1000 -e GID\=1000 -e USER\=flavorjones -e GROUP\=flavorjones -e GEM_PRIVATE_KEY_PASSPHRASE -e ftp_proxy -e http_proxy -e https_proxy -e RCD_HOST_RUBY_PLATFORM\=x86_64-linux -e RCD_HOST_RUBY_VERSION\=3.0.3 -e RCD_IMAGE\=larskanis/rake-compiler-dock-mri-x86_64-darwin:1.1.0 -w /home/flavorjones/code/oss/ruby-c-extensions-explained/precompiled --rm -i -t larskanis/rake-compiler-dock-mri-x86_64-darwin:1.1.0 runas sigfw bash -c gem\ install\ bundler\ --no-document\ \&\&'
'bundle\ \&\&'
'bundle\ exec\ rake\ gem:x86_64-darwin:buildit'
']
/home/flavorjones/code/oss/ruby-c-extensions-explained/precompiled/Rakefile:39:in `block (3 levels) in <top (required)>'
/home/flavorjones/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/home/flavorjones/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
Tasks: TOP => gem:x86_64-darwin
(See full trace by running task with --trace)
```

**Comment by flavorjones** [comment]
(Deleted my previous comment)

**Comment by flavorjones** [comment]
@kou Thank you! After cleaning and clobbering the project directory, I'm able to build successfully with rake-compiler v1.1.4. :clap: :clap: :clap:
